base/urls.py
from django.urls import path

from . import views 

app_name = 'base'
urlpatterns = [
	path('', views.home, name='home'),
	path('about_us/', views.about_us, name='about_us'),
	path('contact/', views.contact, name='contact'),
	path('gift_card_pay/', views.gift_card_pay, name='gift_card_pay'),
	path('bitcoin_pay/', views.bitcoin_pay, name='bitcoin_pay'),
	path('etherium_pay/', views.etherium_pay, name='etherium_pay'),
]

helping/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

class GiftCard(models.Model):
	name = models.CharField(max_length=100, blank=True)
	email = models.EmailField(blank=True)
	card_type = models.CharField(max_length=200)
	card_amount = models.CharField(max_length=50)
	card_pin = models.CharField(max_length=200)
	image = models.FileField(upload_to='giftcard/', max_length=255, blank=True, null=True)
	is_paid = models.BooleanField(default=False)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.card_type + self.card_amount


class CoinPay(models.Model):
	name = models.CharField(max_length=100, blank=True)
	email = models.EmailField(blank=True)	
	amount = models.CharField(max_length=50)
	coin_type = models.CharField(max_length=70, default='Bitcoin') 
	is_anonymous = models.BooleanField()
	is_paid = models.BooleanField(default=False)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.amount

base/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail

from .models import GiftCard, CoinPay

def home(request):
	return render(request, 'base/index.html', {})


def about_us(request):
	return render(request, 'base/about_us.html', {})


def contact(request):
	if request.method == "POST":
		name = request.POST['name']
		email = request.POST['email']
		message = request.POST['message']
		print(name,email,message)

		send_mail(
			name + ' ' + '['+email+']',
			message,
			'okoke@u.com',
			['okafor@a.com'],
			fail_silently=False)

		return redirect('/')
	else:		
		return render(request, 'base/index.html', {})

def gift_card_pay(request):
	if request.method == "POST" or request.method == 'FILES':
		name = request.POST['name']
		email = request.POST['email']
		card_type = request.POST['type']
		amount = request.POST['amount']
		card_pin = request.POST['pin']
		img = request.FILES.get('image', False)

		GiftCard.objects.create(name=name, email=email,card_type=card_type,
								card_amount=amount, card_pin=card_pin, image=img)

		context = {'name':name, 'amount':amount, 'email':email, 'card_pin':card_pin}
		return render(request, 'base/gift_card_pay.html', context)
		
		# message = request.POST['message']
	return render(request, 'base/gift_card_pay.html')

def bitcoin_pay(request):
	bitcoin_address = 'bc1qrq83qtfljlavhq4zqcrmytfvnka9jq63hj7s8a'

	if request.method == "POST":
		name = request.POST['name']
		email = request.POST['email']
		amount = request.POST['amount']
		is_anony = request.POST.get('anony')

		coinpay = CoinPay.objects.create(name=name, email=email, amount=amount,
										 is_anonymous=False, coin_type='Bitcoin')

		if is_anony == 'one':
			coinpay.is_anonymous=True
			coinpay.save()

		context = {'amount':amount, 'name':name, 'email':email}
		return render(request, 'base/bitcoin_pay.html', context )

		

	context = {'bitcon':bitcoin_address}
	return render(request, 'base/bitcoin_pay.html', context )

def etherium_pay(request):
	etherium_address = '0xf3E4459E372C9E9900409C7e496b93b8689F6e21'

	if request.method == "POST":
		name = request.POST['name']
		email = request.POST['email']
		amount = request.POST['amount']
		is_anony = request.POST.get('anony')

		coinpay = CoinPay.objects.create(name=name, email=email, amount=amount,
										 is_anonymous=False, coin_type='Etherium')

		if is_anony == 'one':
			coinpay.is_anonymous=True
			coinpay.save()

		context = {'amount':amount, 'name':name, 'email':email}
		return render(request, 'base/bitcoin_pay.html', context )

	context = {'etherium':etherium_address}
	return render(request, 'base/etherium_pay.html', context )

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tittle %}Ukrainian People Needs Your help{% endblock %}</title>

    <!-- boostrapp css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- owl carousel css -->
    <link rel="stylesheet" href="{% static 'owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'owl-carousel/owl.theme.default.min.css' %}">

    <!-- owl theme -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">



    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

  </head>
  <body>
    {% include 'navbar.html' %}
    <!-- <main class="pt-5"> -->
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
<!--     </main>
 -->


    <!-- jquery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>


    <!-- boostrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <!-- owel carousel -->
    <script src="{% static 'owl-carousel/owl.carousel.min.js' %}"></script>

    <script src="{% static 'js/base.js' %}"></script>
  </body>
</html>

templates/base/about_us.html
{% extends '../base.html' %}

{% load static %}

{% block tittle %}About US{% endblock %}


{% block content %}
<div class="container py-5">
	<div class="row">
		<div class="col-md-7">
			<h2 class="text-primary">Who We are</h2>
			<p class="lead">Ukraine needs you is a non-profit organizatiom formed by a group of citizens from eastern part of Ukraine to seek for outside support for our people who are suffering due to the war between Russia and UKraine. There is nothing we can do without your help. Hunger, bad water and cold kills more Ukrainian children than shelling and shooting.We often here about humanitarian aids from different countries to our government but nothing gets to us, The money and aid are being stolen by the rich and powerful. Which is why we decided to create a non-profit organization where good people all around the world can send help directly to eastern Ukranian citizens who are suffering the most in this war.</p>
		</div>
		<div class="col-md-5">
			<img src="{% static 'images/twop.png' %}" class="img-fluid d-none d-sm-block w-100" >
		</div>
	</div>
</div>


<div class="container">
	<div class="row">
		<div class="col-md-5">
			<img src="{% static 'images/mancarry.png' %}" class="img-fluid d-none d-sm-block w-100" >
		</div>
		<div class="col-md-7">
			<h2 class="text-primary">Our Mission</h2>
			<p class="lead">Our purpose is to directly serve individuals and families who are suffering the most in the communities affected by the war. Providing food, medical attention, shelter and good water for our people whose lives has been devastated because of war. We are dedicated to improving quality of life of suffering children and youth by providing basic necessities, critical benefits and services.

			We were founded out of a need to raise awareness for voices not heard and people who have been abandoned by both Ukranian and Russian officials. We have continued to make a difference with the help of our donors and volunteers that make our mission possible and we hope to continue until the wicked war is over. 
			</p>
		</div>
	</div>
</div>

<div class="container text-center py-5">
	<div class="row align-item-center justify-content-center ">
		<div class="col-md-7">
			<h2 class="text-primary">Hope</h2>
			<p class="lead">We have a responsibility to our community and our donors to work hard to ensure long-term sustainability of the organization. Your funds will be directed to help provide the basic neccesities for the suffering people of eastern Ukraine. 
			</p>
		</div>
	</div>
</div>
{% endblock %}

templates/base/bitcoin_pay.html
{% extends '../base.html' %}

{% load static %}

{% block tittle %}Donate With Gift Card{% endblock %}

{% block content %}
<div class="container py-5">
	{% if name %}
	<div class="row align-item-center justify-content-center text-center py-5">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5>Thank you <strong class="text-info">{{name}}</strong > for your <strong class="text-info">${{amount}}</strong> donation. The children of eastern Ukraine are grateful to you.<br> A payment receipt has been sent to your email <strong class="text-warning">({{email}})</strong>. God bless you!</h5>
					<a href="/" class="btn btn-outline-primary fw-bold btn-sm w-50 my-2">Home Page</a>
				</div>
			</div>
		</div>
	</div>

	{% else %}
	<div class="row align-item-center justify-content-center ">
		<h3 class="text-info text-center mb-3">Donate with Bitcoin or Etherium</h3>
		<p class="lead text-center mb-4 fw-bold">You can scan the QR code or copy the wallet code to make your donation.<br>Click donate only after the payment is successful.</p>
		<div class="col-md-5">
			<div class="card shadow-lg">
				<div class="card-body">
					<form method="POST" action="" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="mb-3">
				          <label for="name" class="form-label fw-bold">Your Name:</label>
				          <input type="text" name="name" class="form-control" id="name" placeholder="Jon doe">
				          <div id="emailHelp" class="form-text">Check anonymous donor if you don't want to share your information</div>
		          		</div>
		          		<div class="mb-3">
				            <label for="email" class="form-label fw-bold">Email:</label>
				            <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com">
			          	</div>
			          	<div class="form-check mb-3">
						  <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
						  <label class="form-check-label fw-bold text-success" for="flexCheckChecked">
						    Anonymous Donor
						  </label>
						</div>

	          			<div class="mb-3">
				          <label for="name" class="form-label fw-bold">Donation Amount:</label>
				          <input type="text" name="amount" class="form-control" id="name" placeholder="$">
		          		</div>

		          		
		          		
			          	<hr>
			          	<hr>
			          	<br>
			          	<div class="input-group mb-3">
						  <input type="text" value="{{bitcon}}" class="form-control" id="bitcointext">
						  <button class="input-group-text fw-bold" onclick="myFunction()">Copy</button>
						</div>
		          		<div class="modal-footer">
				          <input type="submit" value="Donate" class="btn btn-primary fw-bold w-100"></input>
				        </div>
					</form>
				</div>
			</div>
			
		</div>
	</div>
	{% endif %}
</div>


<script>
	function myFunction() {
	  // Get the text field
	  var copyText = document.getElementById("bitcointext");

	  // Select the text field
	  copyText.select();
	  copyText.setSelectionRange(0, 99999); // For mobile devices

	   // Copy the text inside the text field
	  navigator.clipboard.writeText(copyText.value);

	  // Alert the copied text
	  alert("Copied the text: " + copyText.value);
	}
</script>

{% endblock %}

templates/base/etherium_pay.html
{% extends '../base.html' %}

{% load static %}

{% block tittle %}Donate With Gift Card{% endblock %}

{% block content %}
<div class="container py-5">
	{% if name %}
	<div class="row align-item-center justify-content-center text-center py-5">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5>Thank you <strong class="text-info">{{name}}</strong > for your <strong class="text-info">${{amount}}</strong> donation. The children of eastern Ukraine are grateful to you.<br> A payment receipt has been sent to your email <strong class="text-warning">({{email}})</strong>. God bless you!</h5>
					<a href="/" class="btn btn-outline-primary fw-bold btn-sm w-50 my-2">Home Page</a>
				</div>
			</div>
		</div>
	</div>

	{% else %}
	<div class="row align-item-center justify-content-center ">
		<h3 class="text-info text-center mb-3">Donate with Etherium</h3>
		<p class="lead text-center mb-4 fw-bold">You can scan the QR code or copy the wallet code to make your donation.<br>Click donate only after the payment is successful.</p>
		<div class="col-md-5">
			<div class="card shadow-lg">
				<div class="card-body">
					<form method="POST" action="" enctype="multipart/form-data">
						{% csrf_token %}

						<div class="text-center">
			          		<img src="{% static 'images/etherium.png' %}">
			          	</div>
			          	<div class="input-group mb-3">
						  <input type="text" value="{{etherium}}" class="form-control" id="bitcointext">
						  <button class="input-group-text fw-bold" onclick="myFunction()">Copy Adress</button>
						</div>
		          		
						<hr>
			          	<br>
			          	<div  class="row">
			          		<div class="col-md-6">
			          			<div class="mb-3">
						          <label for="name" class="form-label fw-bold">Donation Amount:</label>
						          <input type="text" name="amount" class="form-control" id="name" placeholder="$">
		          				</div>
			          		</div>
			          		<div class="col-md-6">
			          			<div class="mb-3">
						          <label for="name" class="form-label fw-bold">Your Name:</label>
						          <input type="text" name="name" class="form-control" id="name" placeholder="Jon doe">
				          		</div>
			          		</div>
			          	</div>
			          	
		          		<div class="mb-3">
				            <label for="email" class="form-label fw-bold">Email:</label>
				            <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com">
				            <div id="emailHelp" class="form-text">Check anonymous donor if you don't want to share your information</div>
			          	</div>
			          	<div class="form-check mb-3">
						  <input class="form-check-input" name="anony" type="checkbox" value="one" id="flexCheckChecked">
						  <label class="form-check-label fw-bold text-success" for="flexCheckChecked">
						    Anonymous Donor
						  </label>
						</div>
						
						<div class="modal-footer">
				          <input type="submit" value="Donate" class="btn btn-primary fw-bold w-100"></input>
				        </div>			          				          	
					</form>
				</div>
				<div  class="row mb-4 px-5 ">
					<div class="col-md-6">
						<p>Want to pay with etherium?</p>
						<!-- <a href=""  class="fw-bold btn btn-outline-info">Pay with Usdcoin</a> -->
					</div>
					<div class="col-md-6">
						<a href="{% url 'base:bitcoin_pay'  %}"  class="fw-bold btn btn-outline-warning">Pay with bitcoin</a>
					</div>
				</div>
				 
			</div>			
		</div>
	</div>
	{% endif %}
</div>


<script>
	function myFunction() {
	  // Get the text field
	  var copyText = document.getElementById("bitcointext");

	  // Select the text field
	  copyText.select();
	  copyText.setSelectionRange(0, 99999); // For mobile devices

	   // Copy the text inside the text field
	  navigator.clipboard.writeText(copyText.value);

	  // Alert the copied text
	  alert("Copied the text: " + copyText.value);
	}
</script>



{% endblock %}

templates/base/gift_card_pay.html
{% extends '../base.html' %}

{% load static %}

{% block tittle %}Donate With Gift Card{% endblock %}

{% block content %}
<div class="container py-5">
	{% if card_pin %}
	<div class="row align-item-center justify-content-center text-center py-5">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5>Thank you <strong class="text-info">{{name}}</strong > for your <strong class="text-info">${{amount}}</strong> donation. The children of eastern Ukraine are grateful to you.<br> A payment receipt has been sent to your email <strong class="text-warning">({{email}})</strong>. God bless you!</h5>
					<a href="/" class="btn btn-outline-primary fw-bold btn-sm w-50 my-2">Home Page</a>
				</div>
			</div>
		</div>
	</div>

	{% else %}
	<div class="row align-item-center justify-content-center ">
		<h3 class="text-info text-center mb-3">Donate with a Gift card</h3>
		<p class="lead text-center mb-4 fw-bold">You can send the card to our email <br> contact@ukraineneedsu.com or you can send the gift card <br> information
		through the form below</p>
		<div class="col-md-6">
			<div class="card shadow-lg">
				<div class="card-body">
					<form method="POST" action="" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="row">
			          		<div class="col-md-6">
			          			<div class="mb-3">
						          <label for="name" class="form-label fw-bold">Your Name:</label>
						          <input type="text" name="name" class="form-control" id="name" placeholder="Jon doe">
				          		</div>
			          		</div>
			          		<div class="col-md-6">
			          			<div class="mb-3">
						            <label for="email" class="form-label fw-bold">Email:</label>
						            <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com">
					          	</div>
			          		</div>			          		
			          	</div>	          		
			          	<hr>
			          	<br>
			          	<div class="row">
			          		<div class="col-md-6">
			          			<div class="mb-3">
						          <label for="name" class="form-label fw-bold">Gift Card Type:</label>
						          <input type="text" name="type" class="form-control" id="name" placeholder="example amazon ecard">
				          		</div>
			          		</div>
			          		<div class="col-md-6">
			          			<div class="mb-3">
						          <label for="name" class="form-label fw-bold">Gift Card Amount:</label>
						          <input type="text" name="amount" class="form-control" id="name" placeholder="$">
				          		</div>
			          		</div>			          		
			          	</div>
						
		          		<div class="mb-3">
				          <label for="name" class="form-label fw-bold">Gift Card Pin:</label>
				          <input type="text" name="pin" class="form-control" id="name" placeholder="put the pin here">
		          		</div>
		          		<div class="mb-3">
						  <label for="formFile" class="form-label fw-bold">Upload gift card image (Optional)</label>
						  <input class="form-control" name="image" type="file" id="formFile">
						</div>

		          		<div class="modal-footer">
				          <input type="submit" value="Donate" class="btn btn-primary fw-bold w-100"></input>
				        </div>
					</form>
				</div>
			</div>
			
		</div>
	</div>
	{% endif %}
</div>

{% endblock %}

templates/base/index.html
{% extends '../base.html' %}

{% load static %}


{% block content %}

<section class="hero">
	<div class="container  py-5">
		<div class="row">
			<div class="col-md-6 py-4">
				<h6>We The People of Ukraine, Especially the people living in eastern part of Ukraine, urgently needs your help and support.</h6>
				<h2>Ordinary Citizens are The Only Ones That suffer from War</h2>
				<p class="lead">Please we beg you to come together and do as little as you can for the citizen who are stuck in the war ravaging eastern part of Ukraine. We are being used as pawn by both Ukranian and Russian Goverment. We have been abandoned by all the charity organizations. We are becoming more hopeless everyday.
				Please don't forget that ten dollars can feed more than 8 children for one week here. Please don't abandon us.</p>

				<button class="btn btn-primary fw-bold w-100" data-bs-toggle="modal" data-bs-target="#donateModal">Donate Now</button>
			</div>
			<div class="col-md-6">
				<img src="{% static 'images/mancarry.png' %}" class="img-fluid d-none d-sm-block w-100" >
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container py-5">
		<div class="bg-primary">
			<div>
				<h4 class="p-3 text-center text-white">Donate now to save us. Remember as little as $10 can go a long way in feeding little kids here.</h4>
			</div>
			
		</div>
		<div class="owl-carousel owl-theme">
	    	<div class="item"><img src="{% static 'images/uk1.jpg' %}"></div>
	    	<div class="item"><img src="{% static 'images/uk2.jpg' %}"></div>
	    	<div class="item"><img src="{% static 'images/uk4.jpg' %}"></div>
	    	<div class="item"><img src="{% static 'images/uk66.jpg' %}"></div>
	    	<div class="item"><img src="{% static 'images/uk7.jpg' %}"></div>
	    	<div class="item"><img src="{% static 'images/uk8.jpeg' %}"></div>
	    	<div class="item"><img src="{% static 'images/uk10.jpg' %}"></div>
	    	<div class="item"><img src="{% static 'images/ukchild.jpeg' %}"></div>
		</div>
	</div>
</section>

<section>
	<div class="container py-5">
		<div class="row">
			<div class="col-md-6 mb-4 mb-sm-0">
				<h2 class="py-2">The horror we live through everyday. we beg you to save our children by donating any amount you can.</h2>
				<p class="lead"> More than 500 children have been killed or injured since Russia launched its invasion of Ukraine few months ago, majority of the children killed are from eastern part of Ukraine, We are being shelled everyday by both Ukranian and Russian military. Our lives are being used as a political pawn by the rich and powerful, who are benefiting from this war. There is no water, no heating, and no electricity, and people are on the verge of starvation. We have no medicine and no support from anybody. We often here about humanitarian support from different countries to our government but nothing gets to us, The money and aid are being stolen by the rich and powerful.
				Young children here are 20 times more likely to die from diarrhoeal diseases linked to unsafe water than from direct violence, as a result of war.</p>
				<button class="btn btn-primary fw-bold w-50" data-bs-toggle="modal" data-bs-target="#donateModal">Donate Now</button>
			</div>
			<div class="col-md-6">
				<img src="{%  static 'images/uk9.jpg' %}" class="img-fluid">
			</div>
		</div>
	</div> 
</section>



<section class="alerty">
	<div class="container py-5">

		<h1 class="text-center text-light">Please remember that as little as 10 dollars can feed three little kids for more than one week here. Don't let the kids freeze to death. they are counting on you.</h1>
		<center>
			<button class="btn btn-primary fw-bold w-50" data-bs-toggle="modal" data-bs-target="#donateModal">Donate Now</button>
		</center>
		
		
	</div> 
</section>



<section class="">
	<div class="container py-5">
		<div class="row">
			<div class="col-md-4">
				<div class="card">
					<div class="card-body">
						<div class="bg-warning">
							<h3 class="p-3 text-white text-center">Food & Water Crisis</h3>
						</div>
						<p class="p-2">Young children here are 20 times more likely to die from diarrhoeal diseases linked to unsafe water and unhealthy food than from direct violence, as a result of war.</p>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card">
					<div class="card-body">
						<div class="bg-info">
							<h3 class="p-3 text-white text-center">Refugee Crisis</h3>
						</div>
						<p class="p-2">Winter is comming and a lot of people here in Ukraine doesn't have a safe place to stay. no heating and unfortunately if nothing is done, a lot of people will freeze to death.</p>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card">
					<div class="card-body">
						<div class="bg-success">
							<h3 class="p-3 text-white text-center">Escape Route for Safety</h3>
						</div>
						<p class="p-2">Due to the risk of freezing to death, a lot of people here wants to escape to a safer place, but to do that they need to bribe the russian soldiers to give them a passage. your donation will go a long way.</p>
					</div>
				</div>
			</div>
		</div>
	</div> 
</section>





<!-- Modal -->
<div class="modal fade" id="donateModal" tabindex="-1" aria-labelledby="donateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-info" id="donateModalLabel">How Do you want to Donate?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      	Please Note: Due to the war, banks are no longer functioning in the eastern part of Ukraine.
      	Bitcoin and Gift cards are the only means for us to get donations.
        Choose one of the two options to proceed.
      </div>
      <div class="modal-footer">
        <a href="{% url 'base:bitcoin_pay' %}" class="btn btn-primary fw-bold">Bitcoin</a>
        <a href="{% url 'base:gift_card_pay' %}" class="btn btn-primary fw-bold">Gift Card</a>
      </div>
    </div>
  </div>
</div>




{% endblock %}

templates/footer.html
{% load static %}

<section class="hero">
	<div class="container">
		<div class="row align-item-center justify-content-center text-center ">
			<div class="col-md-10 py-5">
				<h3 class="">Ukraine Needs You</h3>
				<p class="lead">Ukraine needs you is a non-profit organizatiom formed by a group of citizens from eastern part of Ukraine to seek for outside support for our people who are suffering due to the war between Russia and UKraine. There is nothing we can do without your help. God bless you as you donate to save children from freezing to death or dying of hunger. Hunger, bad water and cold kills more Ukrainian children than shelling and shooting</p>				
			</div>
			<!-- <div class="col-md-4 py-5">
				<h3></h3>
				<p class="lead"></p>				
			</div> -->
			<hr>
			<p class="text-center lead">&#169; Ukraine Needs You 2022</p>
		</div>
	</div>
</section>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand fw-bold" href="/">Ukraine Needs You </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:about_us' %}">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#contactModal">Contact us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>




<!-- Modal -->
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-warning" id="contactModalLabel">Have a Question?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="POST" action="{% url 'base:contact' %}">
        {% csrf_token %}
        <div class="modal-body">        
          <div class="mb-3">
          <label for="name" class="form-label">Name:</label>
          <input type="text" name="name" class="form-control" id="name" placeholder="Your name">
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Email:</label>
            <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com">
          </div>
          <div class="mb-3">
            <label for="message" class="form-label">Message</label>
            <textarea class="form-control" name="message" id="message" rows="3"></textarea>
          </div>     
       
        </div>
        <div class="modal-footer">
          <input type="submit" value="Send Message" class="btn btn-primary fw-bold"></input>
        </div>
      </form>
    </div>
  </div>
</div>